//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BloomingFlower.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MyDbContext : DbContext
    {
        public MyDbContext()
            : base("name=MyDbContext")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AcademicActivitiesImagesInfo> AcademicActivitiesImagesInfoes { get; set; }
        public virtual DbSet<AcademicActivitiesVideosInfo> AcademicActivitiesVideosInfoes { get; set; }
        public virtual DbSet<ExtraActivitiesImagesInfo> ExtraActivitiesImagesInfoes { get; set; }
        public virtual DbSet<ExtraActivitiesVideoInfo> ExtraActivitiesVideoInfoes { get; set; }
        public virtual DbSet<ImageInfo> ImageInfoes { get; set; }
        public virtual DbSet<NewsAndEventsInfo> NewsAndEventsInfoes { get; set; }
        public virtual DbSet<SliderImage> SliderImages { get; set; }
        public virtual DbSet<UsersInfo> UsersInfoes { get; set; }
        public virtual DbSet<VideosInfo> VideosInfoes { get; set; }
        public virtual DbSet<RegisterUserInfo> RegisterUserInfoes { get; set; }
    }
}
